# Generated by Django 6.0.7 on 2026-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='training',
            name='duration',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_road_village',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana_upzila',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='educations',
            field=models.ManyToManyField(to='candidates.education'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='employments',
            field=models.ManyToManyField(to='candidates.employment'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='extracurricular_activities',
            field=models.ManyToManyField(to='candidates.extracurricularactivity'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='portfolios_publications_projects',
            field=models.ManyToManyField(to='candidates.portfoliopublicationproject'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='references',
            field=models.ManyToManyField(to='candidates.reference'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(to='candidates.skill'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='trainings',
            field=models.ManyToManyField(to='candidates.training'),
        ),
        migrations.AlterField(
            model_name='education',
            name='board_university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('ssc', 'SSC'), ('hsc', 'HSC'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='dept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='scale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='organization_business',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='organization_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employment',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='position_held',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email_alt',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_number_alt',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliopublicationproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliopublicationproject',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfoliopublicationproject',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reference',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone_office',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='reference',
            name='relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
