# Generated by Django 6.1 on 2026-09-01 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_address_district_alter_address_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major_group_type',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('arts', 'Arts / Humanities'), ('commerce', 'Commerce / Business Studies'), ('not_applicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=50),
        ),
        migrations.AddField(
            model_name='portfoliopublicationproject',
            name='item_type',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('publication', 'Publication / Research'), ('portfolio', 'Portfolio Website'), ('award', 'Award / Achievement'), ('other', 'Other')], default='project', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in feet (e.g., 5.8)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Bangladeshi', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number_alt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christianity', 'Christianity'), ('buddhism', 'Buddhism'), ('judaism', 'Judaism'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_title',
            field=models.CharField(blank=True, help_text='e.g., BSc in Computer Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('ssc', 'SSC / Equivalent'), ('hsc', 'HSC / Equivalent'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 4 Years', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_group',
            field=models.CharField(blank=True, help_text='e.g. Physics, Accounting', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2031)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='scale',
            field=models.CharField(blank=True, choices=[('4.00', 'Out of 4.00'), ('5.00', 'Out of 5.00'), ('10.00', 'Out of 10.00'), ('100', 'Out of 100 (Percentage)'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='organization_business',
            field=models.CharField(blank=True, help_text='e.g., Software IT, Bank', max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phone_office',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='e.g., 2.5', max_digits=4, null=True),
        ),
    ]
