# Generated by Django 6.0.7 on 2026-07-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_personalinfo_email_remove_training_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='educations',
            field=models.ManyToManyField(blank=True, to='candidates.education'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='employments',
            field=models.ManyToManyField(blank=True, to='candidates.employment'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='extracurricular_activities',
            field=models.ManyToManyField(blank=True, to='candidates.extracurricularactivity'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='portfolios_publications_projects',
            field=models.ManyToManyField(blank=True, to='candidates.portfoliopublicationproject'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='references',
            field=models.ManyToManyField(blank=True, to='candidates.reference'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='candidates.skill'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='candidates.training'),
        ),
    ]
