# Generated by Django 6.0.7 on 2026-07-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=30, help_text='Duration of the interview in minutes')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Link for virtual interviews', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
